{
  "swagger": "2.0",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "authorization",
      "in": "header"
    },
  },
  "paths": {
    "/get_user/{id}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "summary": "user",
        "tags": [
          "User"
        ],
        "description": "Get user by id",
        "operationId": "getUser",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "User id",
            "required": true,
            "type": "integer"
          }
        
        ],
        "consumes": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/sign_up": {
      "post": {
        "summary": "sign up",
        "tags": [
          "User"
        ],
        "description": "Sign up",
        "operationId": "signUp",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "description": "User",
            "required": true,
          }
        ],
        "consumes": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/sign_in": {
      "post": {
        "summary": "sign up",
        "tags": [
          "User"
        ],
        "description": "Sign up",
        "operationId": "signUp",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "description": "User",
            "required": true,            
          }
        ],
        "consumes": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },

  },

  
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "127.0.0.1:3000"
        }
      }
    }
  ]
}